name: Carl Legarde
favicon: null
layout_spectrum: 0.48676
typography_spectrum: 0.29189
title: Beta Tanks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000002'
    - '#f7f8fc'
    - '#96c2ef'
    - '#fec400'
    - '#6c7177'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
