name: Carl Legarde
favicon: null
layout_spectrum: 0.24616
typography_spectrum: 0.2509
title: Beta Test X
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e6f0f1'
    - '#81a1d0'
    - '#576474'
    - '#ad4000'
  brandStrength: 0.506941898027435
  lightness: 0.2908532749861479
  saturation: 0.8028084828983992
  rhythmicContrast: 0.5
purpose: []
