name: Carl Legarde
favicon: null
layout_spectrum: 0.3235293976031244
typography_spectrum: 0.7346080387942493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.506941898027435
  lightness: 0.2908532749861479
  saturation: 0.8028084828983992
  rhythmicContrast: 0.5616279281675816
purpose: []
